sub_a_cols = [
    "SeriesID",
    "SeriesDescription",
    "GeoAreaCode",
    "GeoAreaName",
    "TimePeriod",
    "Value",
    "Time_Detail",
    "Source",
    "FootNote",
    "Nature",
    "Units",
    "Reporting Type",
    "Observation Status",
    "Bioclimatic Belt",
    "ISOalpha3",
    "Type",
    "SeriesCode",
]

sub_a_landtype_cols = [
    "SeriesID",
    "SeriesDescription",
    "GeoAreaCode",
    "GeoAreaName",
    "TimePeriod",
    "Value",
    "Time_Detail",
    "Source",
    "FootNote",
    "Nature",
    "Units",
    "Reporting Type",
    "Observation Status",
    "Bioclimatic Belt",
    "Land Type",
    "ISOalpha3",
    "Type",
    "SeriesCode",
]

sub_b_perc_cols = [
    "SeriesID",
    "SeriesDescription",
    "GeoAreaCode",
    "GeoAreaName",
    "TimePeriod",
    "Value",
    "Time_Detail",
    "Source",
    "FootNote",
    "Nature",
    "Units",
    "Reporting Type",
    "Observation Status",
    "Bioclimatic Belt",
    "ISOalpha3",
    "Type",
    "SeriesCode",
]

sub_b_landtype_cols = [
    "SeriesID",
    "SeriesDescription",
    "GeoAreaCode",
    "GeoAreaName",
    "TimePeriod",
    "Value",
    "Time_Detail",
    "Source",
    "FootNote",
    "Nature",
    "Units",
    "Reporting Type",
    "Observation Status",
    "Impact Type",
    "Bioclimatic Belt",
    "ISOalpha3",
    "Type",
    "SeriesCode",
]
