mountain_area_cols = [
    "Indicator",
    "SeriesID",
    "SERIES",
    "SeriesDesc",
    "REF_AREA",
    "GeoAreaName",
    "TIME_PERIOD",
    "TIME_DETAIL",
    "SOURCE_DETAIL",
    "COMMENT_OBS",
    "NATURE",
    "OBS_STATUS",
    "UNIT_MEASURE",
    "UNIT_MULT",
    "BIOCLIMATIC_BELT",
    "OBS_VALUE",
    "OBS_VALUE_RSA",
]


sub_a_cols = [
    "Indicator",
    "SeriesID",
    "SERIES",
    "SeriesDesc",
    "REF_AREA",
    "GeoAreaName",
    "TIME_PERIOD",
    "TIME_DETAIL",
    "SOURCE_DETAIL",
    "COMMENT_OBS",
    "NATURE",
    "OBS_STATUS",
    "UNIT_MEASURE",
    "UNIT_MULT",
    "BIOCLIMATIC_BELT",
    "LAND_COVER",
    "OBS_VALUE",
]

sub_a_landtype_cols = [
    "Indicator",
    "SeriesID",
    "SERIES",
    "SeriesDesc",
    "REF_AREA",
    "GeoAreaName",
    "TIME_PERIOD",
    "TIME_DETAIL",
    "SOURCE_DETAIL",
    "COMMENT_OBS",
    "NATURE",
    "OBS_STATUS",
    "UNIT_MEASURE",
    "UNIT_MULT",
    "BIOCLIMATIC_BELT",
    "LAND_COVER",
    "OBS_VALUE",
    "OBS_VALUE_RSA",
]

sub_b_landtype_cols = [
    "Indicator",
    "SeriesID",
    "SERIES",
    "SeriesDesc",
    "REF_AREA",
    "GeoAreaName",
    "TIME_PERIOD",
    "TIME_DETAIL",
    "SOURCE_DETAIL",
    "COMMENT_OBS",
    "NATURE",
    "OBS_STATUS",
    "UNIT_MEASURE",
    "UNIT_MULT",
    "BIOCLIMATIC_BELT",
    "OBS_VALUE",
    "OBS_VALUE_RSA",
    "OBS_VALUE_NET",
    "OBS_VALUE_RSA_NET",
]

sub_b_perc_cols = [
    "Indicator",
    "SeriesID",
    "SERIES",
    "SeriesDesc",
    "REF_AREA",
    "GeoAreaName",
    "TIME_PERIOD",
    "TIME_DETAIL",
    "SOURCE_DETAIL",
    "COMMENT_OBS",
    "NATURE",
    "OBS_STATUS",
    "UNIT_MEASURE",
    "UNIT_MULT",
    "BIOCLIMATIC_BELT",
    "OBS_VALUE",
    "OBS_VALUE_NET",
]
