name: Build
# To test with act: gh act --secret-file $ENV_FILE --workflows .github/workflows/unit.yml
# test
on:
  push:
    branches:
      - main
  pull_request:

env:
  EARTHENGINE_TOKEN: ${{ secrets.EARTHENGINE_TOKEN }}
  PYTHONUNBUFFERED: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python "3.10"
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install sepal_ui
        run: python -m pip install sepal_ui
      - name: Build with sepal_ui venv
        run: module_venv
      - name: Install nox
        run: python -m pip install nox
      - name: set entry point and run tests
        run: nox -s test_ui
      - name: test functions
        run: nox -s test
